/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itheima_pressure_MainActivity */

#ifndef _Included_com_itheima_pressure_MainActivity
#define _Included_com_itheima_pressure_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itheima_pressure_MainActivity
 * Method:    getPressure
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itheima_pressure_MainActivity_getPressure
  (JNIEnv *, jobject);

/*
 * Class:     com_itheima_pressure_MainActivity
 * Method:    uninstalllistener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_itheima_pressure_MainActivity_uninstalllistener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
