/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ccallbackjava_JNI */

#ifndef _Included_com_example_ccallbackjava_JNI
#define _Included_com_example_ccallbackjava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ccallbackjava_JNI
 * Method:    callBackJava_helloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccallbackjava_JNI_callBackJava_1helloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccallbackjava_JNI
 * Method:    callBackJava_add
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccallbackjava_JNI_callBackJava_1add
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccallbackjava_JNI
 * Method:    callBackJava_printString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccallbackjava_JNI_callBackJava_1printString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ccallbackjava_JNI
 * Method:    callBackJava_hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ccallbackjava_JNI_callBackJava_1hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
